Desktop version
alexmedinasf/Porfolio pull request #6
Opened 2022-08-23 21:32 UTC by alexmedinasf

Created a desktop version for the Portfolio.

Created a new CSS file to style the desktop version of the website

2022-08-23 22:20 UTC, omarsalem7 requested changes
Hi @alexmedinasf 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- Descriptive pull request ✔️
- No linter errors ✔️
- Descriptive commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 22:20 UTC, omarsalem7 commented on index.html
> +				</ul>
- [ ] Kindly remove the hamburger menu from the desktop version by adding `display:none` in the desktop version.
- [ ] Kindly remove the underline from nav-links to match it like the Figma.
- [ ] Also consider adding the appropriate space to right and left to be like the Figma.

2022-08-23 22:20 UTC, omarsalem7 commented on css/desktop-style.css
> +}
- [ ] Kindly make feature-project align with projects section like the Figma.

- [ ] Alos consider styling languages in the feature project as stated in the following image.

| Your design  | Figma design|
| ------------- | ------------- |
| ![2022_08_24_009_Kleki](https://user-images.githubusercontent.com/53402600/186275149-c8e7a617-7da7-4f75-9271-46c62ba8a1c4.png)  |![image](https://user-images.githubusercontent.com/53402600/186275191-f853d86d-b679-4b14-a2ba-283ae5919674.png)|

2022-08-23 22:20 UTC, omarsalem7 commented on css/desktop-style.css
> +
- [ ] Kindly use the correct background color as Figma. Color code: #FFFFFF

2022-08-24 14:38 UTC, ShahierNashaat approved these changes
Hi @alexmedinasf, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 

- Correct use of GitFlow ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️
- Your readme looks professional ✔️
- Good overall design ✔️
- Your code is clean and well documented ✔️

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 14:38 UTC, ShahierNashaat commented on css/desktop-style.css
> +  margin-left: 895px;
- [ ] [Optional] Kindly be noticed that to remove the horizontal scroll bar you have to remove the `margin-left: 895px;` and add these CSS lines.
```css
    position: absolute;
    right: 0;
```

2022-08-24 14:44 UTC, merged